# Generated by Django 4.1.5 on 2023-02-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
